src/Entity/Annonces.php
<?php

namespace App\Entity;

use App\Repository\AnnoncesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=AnnoncesRepository::class)
 * @ORM\Table(name="annonces", indexes={@ORM\Index(columns={"title", "content"}, flags={"fulltext"})})
 */
class Annonces
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="annonces", orphanRemoval=true,cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\ManyToMany(targetEntity=Users::class, inversedBy="favoris")
     */
    private $favoris;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="annonces", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->favoris = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    public function setCategories(?Categories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAnnonces($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAnnonces() === $this) {
                $image->setAnnonces(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Users[]
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Users $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris[] = $favori;
        }

        return $this;
    }

    public function removeFavori(Users $favori): self
    {
        if ($this->favoris->contains($favori)) {
            $this->favoris->removeElement($favori);
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAnnonces($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAnnonces() === $this) {
                $comment->setAnnonces(null);
            }
        }

        return $this;
    }
}

src/Controller/Admin/AnnoncesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Annonces;
use App\Repository\AnnoncesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/annonces", name="admin_annonces_")
 * @package App\Controller\Admin
 */
class AnnoncesController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(AnnoncesRepository $annoncesRepo)
    {
        return $this->render('admin/annonces/index.html.twig', [
            'annonces' => $annoncesRepo->findAll()
        ]);
    }

    /**
     * @Route("/activer/{id}", name="activer")
     */
    public function activer(Annonces $annonce)
    {
        $annonce->setActive(($annonce->getActive())?false:true);

        $em = $this->getDoctrine()->getManager();
        $em->persist($annonce);
        $em->flush();

        return new Response("true");
    }

    /**
     * @Route("/supprimer/{id}", name="supprimer")
     */
    public function supprimer(Annonces $annonce)
    {
        $images = $annonce->getImages();
        
        if($images){
            // On boucle sur les images de l'annonce
            foreach($images as $image){
                // On "génère" le chemin physique de l'image
                $nomImage = $this->getParameter("images_directory") . '/' . $image->getName();
                
                // On vérifie si l'image existe
                if(file_exists($nomImage)){
                    unlink($nomImage);
                }
            }
        }

        $em = $this->getDoctrine()->getManager();
        $em->remove($annonce);
        $em->flush();

        $this->addFlash('message', 'Annonce supprimée avec succès');
        return $this->redirectToRoute('admin_annonces_home');
    }
}

src/Controller/AnnoncesController.php
<?php

namespace App\Controller;

use App\Entity\Annonces;
use App\Entity\Comments;
use App\Entity\Images;
use App\Form\AnnonceContactType;
use App\Form\AnnoncesType;
use App\Form\CommentsType;
use App\Repository\AnnoncesRepository;
use App\Service\ManagePictureService;
use App\Service\SendMailService;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/annonces", name="annonces_")
 * @package App\Controller
 */
class AnnoncesController extends AbstractController
{
    // TODO: Fonction index sera une fonction qui affichera les annocnes selon le id de l'user liés à mes annonces dans le compte profil
    /**
     * @Route("/", name="home")
     * @return void
     */
    public function index(AnnoncesRepository $annoncesRepo, Request $request)
    {
        // On définit le nombre d'éléments par page
        $limit = 10;

        // On récupère le numéro de page
        $page = (int)$request->query->get("page", 1);

        // On récupère les annonces de la page
        $annonces = $annoncesRepo->getPaginatedAnnonces($page, $limit);

        // On récupère le nombre total d'annonces
        $total = $annoncesRepo->getTotalAnnonces();

        return $this->render('annonces/index.html.twig', compact('annonces', 'total', 'limit', 'page'));
    }

    /**
     * @Route("/ajout", name="ajout")
     */
    public function ajoutAnnonce(Request $request, ManagePictureService $managePictureService)
    {
        $annonce = new Annonces;

        $form = $this->createForm(AnnoncesType::class, $annonce);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annonce->setUsers($this->getUser());
            $annonce->setActive(false);
            // On récupère les images transmises
            $images = $form->get('images')->getData();

            //Ajout des images via le service
            //$managePictureService->addImages($images, $annonce);

            // On boucle sur les images
            foreach ($images as $image) {
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();

                // On copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

                // On crée l'image dans la base de données
                $img = new Images();
                $img->setName($fichier);
                $annonce->addImage($img);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($annonce);
            $em->flush();

            return $this->redirectToRoute('app_home');
        }

        return $this->render('annonces/ajout.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function editAnnonce(Annonces $annonce, Request $request, ManagePictureService $managePictureService)
    {
        //restreint l'edition de l'annonce si on est pas propriétaire
        $this->denyAccessUnlessGranted('annonce_edit', $annonce);

        $form = $this->createForm(AnnoncesType::class, $annonce);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annonce->setActive(false);
            // On récupère les images transmises
            $images = $form->get('images')->getData();

            // Refacto par un service gestion d' images
            $managePictureService->addImages($images, $annonce);

             /* // On boucle sur les images
            foreach ($images as $image) {
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();

                // On copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

                // On crée l'image dans la base de données
                $img = new Images();
                $img->setName($fichier);
                $annonce->addImage($img);
            }*/
            $em = $this->getDoctrine()->getManager();
            $em->persist($annonce);
            $em->flush();

            return $this->redirectToRoute('annonces_home');
        }

        return $this->render('annonces/ajout.html.twig', [
            'form' => $form->createView(),
            'annonce' => $annonce
        ]);
    }

    /**
     * @Route("/details/{slug}", name="details")
     */
    public function details($slug, AnnoncesRepository $annoncesRepo, Request $request, SendMailService $mailService)
    {
        $annonce = $annoncesRepo->findOneBy(['slug' => $slug]);

        if (!$annonce) {
            throw new NotFoundHttpException('Pas d\'annonce trouvée');
        }

        //Formulaire d'envoie de message à l'auteur (modal)
        $form = $this->createForm(AnnonceContactType::class);

        $contact = $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Envoie de mail (refacto par une création de service send mail)
            $context = [
                'annonce' => $annonce,
                'mail' => $contact->get('email')->getData(),
                'message' => $contact->get('message')->getData()
            ];
            $mailService->send(
                $contact->get('email')->getData(),
                $annonce->getUsers()->getEmail(),
                'Contact au sujet de votre annonce "' . $annonce->getTitle() . '"',
                'contact_annonce',
                $context
            );
            // On crée le mail (sans le service sendmail)
            /*$email = (new TemplatedEmail())
                ->from($contact->get('email')->getData())
                ->to($annonce->getUsers()->getEmail())
                ->subject('Contact au sujet de votre annonce "' . $annonce->getTitle() . '"')
                ->htmlTemplate('emails/contact_annonce.html.twig')
                ->context([
                    'annonce' => $annonce,
                    'mail' => $contact->get('email')->getData(),
                    'message' => $contact->get('message')->getData()
                ]);
            // On envoie le mail
            $mailer->send($email);*/

            // On confirme et on redirige
            $this->addFlash('message', 'Votre e-mail a bien été envoyé');
            return $this->redirectToRoute('annonces_details', ['slug' => $annonce->getSlug()]);
        }

        //PARTIE COMMENTAIRE
        $comment = new Comments;

        $commentForm = $this->createForm(CommentsType::class, $comment);

        $commentForm->handleRequest($request);

        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $comment->setCreatedAt(new \DateTimeImmutable());
            $comment->setAnnonces($annonce);

            //on récupère le contenu de parentid
            $parentid = $commentForm->get("parentid")->getData();
            //dd($parentid);
            //on va chercher le commentaire correspondant
            $em = $this->getDoctrine()->getManager();
            if ($parentid != null) {
                $parent = $em->getRepository(Comments::class)->find($parentid);
            }
            //on définit le parent
            $comment->setParent($parent ?? null);

            $em->persist($comment);
            $em->flush();

            $this->addFlash('message', 'Votre commentaire a bien été envoyé!!');
            return $this->redirectToRoute('annonces_details', ['slug' => $annonce->getSlug()]);
        }


        return $this->render('annonces/details.html.twig', [
            'annonce' => $annonce,
            'form' => $form->createView(),
            'commentForm' => $commentForm->createView()
        ]);
    }

    /**
     * @Route("/supprimer/{id}", name="supprimer")
     */
    public function supprimer(Annonces $annonce)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($annonce);
        $em->flush();

        $this->addFlash('message', 'Annonce supprimée avec succès');

        return $this->redirectToRoute('app_home');
    }

    /**
     * @Route("/favoris/ajout/{id}", name="ajout_favoris")
     */
    public function ajoutFavoris(Annonces $annonce)
    {
        if (!$annonce) {
            throw new NotFoundHttpException('Pas d\'annonce trouvée');
        }
        $annonce->addFavori($this->getUser());

        $em = $this->getDoctrine()->getManager();
        $em->persist($annonce);
        $em->flush();
        return $this->redirectToRoute('app_home');
    }

    /**
     * @Route("/favoris/retrait/{id}", name="retrait_favoris")
     */
    public function retraitFavoris(Annonces $annonce)
    {
        if (!$annonce) {
            throw new NotFoundHttpException('Pas d\'annonce trouvée');
        }
        $annonce->removeFavori($this->getUser());

        $em = $this->getDoctrine()->getManager();
        $em->persist($annonce);
        $em->flush();
        return $this->redirectToRoute('app_home');
    }

    /**
     * @Route("/supprime/image/{id}", name="delete_image", methods={"DELETE"})
     */
    public function deleteImage(Images $image, Request $request)
    {
        $data = json_decode($request->getContent(), true);

        // On vérifie si le token est valide
        if ($this->isCsrfTokenValid('delete' . $image->getId(), $data['_token'])) {
            // On récupère le nom de l'image
            $nom = $image->getName();
            // On supprime le fichier

templates/annonces/ajout.html.twig
{% extends 'users.html.twig' %}

{% block title %}Ajouter une annonce{% endblock %}

{% block body %}
{% if app.request.attributes.get('_route') == 'annonces_edit' %}
    <h1>Modifier une annonce</h1>
{% else %}
    <h1>Ajouter une annonce</h1>
{% endif %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_rest(form) }}

    {# Si la route est "annonces_edit on affiche les images #}
	{% if app.request.attributes.get('_route') == 'annonces_edit' %}
        <h2>Images</h2>
        {% for image in annonce.images %}
            <div>
                <img src="{{ asset('/uploads/images/annonces/'~image.name) }}" alt="" width="150">

                {# On ajoute un lien permettant de supprimer une image (sera géré en Ajax) #}
                <a href="{{ path('annonces_delete_image', {id: image.id})}}" data-delete data-token="{{ csrf_token('delete' ~ image.id )}}">Supprimer</a>
            </div>
        {% endfor %}
    {% endif %}
{{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/images.js') }}"></script>
{% endblock %}

templates/annonces/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ annonce.title }}
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"/>
{% endblock %}
{% block body %}
    <div class="container mt-5">
        {% for message in app.flashes('message') %}
            <div class="p-3 my-2 rounded-2 success">{{ message }}</div>
        {% endfor %}

        <div class="caroulix" id="annonces-carousel" data-ax="caroulix" data-ax-caroulix-autoplay-enabled="true"
             data-caroulix-indicators-enabled="true">
            {% for image in annonce.images %}
                <div class="caroulix-item">
                    <img src={{ asset('uploads/images/annonces/' ~ image.name)|imagine_filter('banniere') }}
                         alt={{ annonce.title|raw }} />
                </div>
            {% endfor %}
        </div>
        <div class="grix xs2 sm3 gutter-0 card">
            <div class="primary flex vcenter fx-center"></div>
            <div class="col-sm2">
                <div class="card-header">{{ annonce.title }}</div>
                <div class="card-content">
                    <p>Catégorie :
                        <strong>{{ annonce.categories.name }}</strong></p>
                    <p>
                        {{ annonce.content|raw }}
                    </p>
                    <p>
                        <button class="btn magenta light-1 rounded-1 shadow-1 press modal-trigger float-right"
                                data-target="modal-contact">Contacter l'annonceur
                        </button>
                    </p>
                    <hr />
                    {% if is_granted("annonce_edit", annonce) %}
                    <p>
                        <a class="txt-orange" href="{{ path("annonces_edit", {id: annonce.id }) }}">Editer l'annonce</a>
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>

        {# Ajout de commentaire #}
        <div class="grix xs2 sm3 gutter-O card">
            <div class="col-xs2 col-sm3">
                <h2>Liste des commentaires</h2>
                {% for comment in annonce.comments %}
                    {% if comment.parent == null %}
                        <h5>Commentaire de: {{ comment.pseudo }}</h5>
                        <div>{{ comment.content|raw }}</div>
                        <p><strong>Publié le </strong> {{ comment.createdAt|date("d/m/Y") }}
                        </p>
                        <p><a href="#ajout-commentaire" data-reply data-id="{{ comment.id }}"
                              class="txt-orange">Reply</a></p>
                        {# On affiche les réponses #}
                        {% for reply in comment.replies %}
                            <div>{{ reply.content|raw }}</div>
                            <p><strong>Réponse publiée par </strong> {{ reply.pseudo }}
                                le {{ reply.createdAt|date("d/m/Y") }}</p>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-xs2 col-sm3" id="ajout-commentaire">
                <h2>Ajouter un commentaire</h2>
                {{ form_start(commentForm) }}
                    {{ form_row(commentForm.pseudo) }}
                    {{ form_row(commentForm.email) }}
                    <p>Message</p>
                    <div id="editor"></div>
                {{ form_end(commentForm) }}
            </div>
        </div>
    </div>

    {# Modal denvoi de mail à l'auteur #}
    <div class="modal shadow-1 white falling" id="modal-contact" data-ax="modal">
        <div class="container">
            <div class="modal-header">Contactez l'annonceur</div>
            <div class="divider"></div>
            {{ form_start(form) }}
            <div class="modal-content"></div>
            <div class="form-field">
                {{ form_row(form.title) }}
            </div>
            <div class="form-field">
                {{ form_row(form.email) }}
            </div>
            <div class="form-field">
                {{ form_row(form.message) }}
            </div>
            <div class="divider"></div>
            <div class="modal-footer">
                <button class="ml-auto btn shadow-1 rounded-1 small orange light-1">Envoyer</button>
                <button data-target="modal-contact"
                        class="ml-auto btn shadow-1 rounded-1 small magenta light-1 modal-trigger">Fermer
                </button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('ckeditor5/ckeditor.js') }}"></script>
    <script src="{{ asset('js/ckeditor.js') }}"></script>
    <script>
        window.onload = () => {
            document.querySelector("#modal-contact").value = "{{ annonce.title|raw }}"

            //on met un écouteur d'event sur tous les reply pour les rediriger vers la form ajout com
            document.querySelectorAll("[data-reply]").forEach(element => {
                element.addEventListener("click", function () {
                    document.querySelector("#comments_parentid").value = this.dataset.id;
                })
            })
        }
        let caroulix = new Axentix.Caroulix('#carousel');
        let modal = new Axentix.Modal('#modal-contact');
    </script>
{% endblock %}

templates/annonces/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des annonces{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"/>
{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="txt-center">Mes annonces: </h1>
        {% for annonce in annonces %}
            <div class="card shadow-1 rounded-1 fx-row mb-5">
                <div class="d-flex vcenter fx-center px-4">
                    <img src="{{ asset('uploads/images/annonces/' ~ annonce.images[0].name)|imagine_filter('square') }}"
                         alt="{{ annonce.title }}"
                         class="card-img-top rounded-2 p-1"
                    >
                </div>
                <div class="flex fx-col fx-grow">
                    <div class="card-header"><a
                                href="{{ path('annonces_details', {slug: annonce.slug}) }}">{{ annonce.title }}</a>
                    </div>
                    <div class="card-content">
                        <p>Catégorie : {{ annonce.categories.name }}</p>
                        <p>
                            {{ annonce.content|striptags|u.truncate(50, '...') }}
                        </p>
                        <div class="txt-red">
                            {% if is_granted("ROLE_USER") %}
                                {% set isFavorite = false %}
                                {% for favoris in annonce.favoris %}
                                    {% if favoris.id == app.user.id %}
                                        {% set isFavorite = true %}
                                    {% endif %}
                                {% endfor %}
                                {% if isFavorite %}
                                    <a href="{{ path('annonces_retrait_favoris', {id: annonce.id}) }}"><i
                                                class="fas fa-heart"></i></a>
                                {% else %}
                                    <a href="{{ path('annonces_ajout_favoris', {id: annonce.id}) }}"><i
                                                class="far fa-heart"></i></a>
                                {% endif %}

                            {% else %}
                                <i class="far fa-heart"></i>
                            {% endif %}

                        </div>
                    </div>
                    <div class="text-center float-right pr-3">
                        <a href="{{ path("annonces_edit", {id: annonce.id}) }}" class="btn shadow-1 rounded-1 yellow"> Modifier </a>
                        <a href="#" class="btn primary shadow-1 rounded-1 modal-trigger" data-target="modal-delete" data-id="{{annonce.id}}" data-titre="{{annonce.title}}">Supprimer</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        {#Pagination #}
        {#<ul class="pagination">
            <li class="{{ (page == 1) ? 'disabled' : '' }}">
                <a href="?page=1">
                    <i class="fas fa-step-backward"></i>
                </a>
            </li>
            <li class="{{ (page == 1) ? 'disabled' : '' }}">
                <a href="{{ (page > 1) ? '?page=' ~ (page - 1) : '' }}">
                    <i class="fas fa-angle-left"></i>
                </a>
            </li>
            {% set pages = (total / limit)|round(0, 'ceil') %}
            {% for item in 1..pages %}
                <li class="{{ (page == item) ? 'active' : '' }}">
                    <a href="?page={{ item }}">{{ item }}</a>
                </li>
            {% endfor %}
            <li class="{{ (page == pages) ? 'disabled' : '' }}">
                <a href="{{ (page < pages) ? '?page=' ~ (page + 1) : '' }}">
                    <i class="fas fa-angle-right"></i>
                </a>
            </li>
            <li class="{{ (page == pages) ? 'disabled' : '' }}">
                <a href="?page={{ pages }}">
                    <i class="fas fa-step-forward"></i>
                </a>
            </li>

        </ul>#}
    </div>
{% endblock %}